from tests.test_cases.service import (
    TEST_USERS_GET_MOCK,
    TEST_USERS_CREATE_MOCK,
    TEST_TASKS_GET_MOCK,
    TEST_TASKS_CREATE_MOCK
)

from tests.test_cases.user_routes import TEST_USER_ROUTE_CREATE_PARAMS, TEST_USER_ROUTE_GET_PARAMS

__all__ = [
    "TEST_USERS_GET_MOCK",
    "TEST_USERS_CREATE_MOCK",
    "TEST_TASKS_GET_MOCK",
    "TEST_TASKS_CREATE_MOCK",
    "TEST_USER_ROUTE_CREATE_PARAMS",
    "TEST_USER_ROUTE_GET_PARAMS"
]