FROM python:3.12.3-slim

RUN pip install poetry

WORKDIR /app

COPY pyproject.toml poetry.lock /app/

RUN poetry install --no-root

COPY . /app/

ENV PYTHONPATH=/app

EXPOSE 8000

CMD ["poetry", "run", "python", "src/rabbitmq/consumer.py"]