services:
  db:
    image: postgres:13
    container_name: db
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - tasks

  app:
    build: .
    container_name: app
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - tasks


volumes:
  pgdata:

networks:
  tasks:
    driver: bridge
